# Generated by Django 5.2.5 on 2025-08-19 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 8, 19)),
        ),
    ]
